### PR TITLE
Smashing magazine

### PR DESCRIPTION
**Pull request by okusarobert**
> This PR implements a heatmap of the smashingmagazine.com homepage
> We css design best practices

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required

### Hello team,

**Great job on your project. However, there a few issues to work on:**

# Mandatory

1). **The background colours are not shades of grey, as required from the odin project.**

Screenshot_2020-09-21 Project Design Teardown The Odin Project

- **Hint: Example of greys that are acceptable #333333, #A1A1A1, #6D6D6D.**

2). **The image logo, with the red pixes, is not required. Instead, use divs that have the same visual weight and are stand-ins for the images. Also, note that all elements should be grayscale color (black, white, or any shade of gray).**

3). **Add some text to help with the visual weight and feel of the page, as mentioned on Odin.**

Screenshot_2020-09-21 Project Design Teardown The Odin Project(1)

4). **The live demo link doesn't work.**

5).  **The pull request brief description explains that this project is a responsive design clone but it is a heatmap.**

6). **Add .DS_Store file to gitignore because it is not related to the project.**

7). **Make sure to build your layout using a width of 1440px on the original page. You can use the Developer Tools to match that screen size.**

- ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/design_teardown/pageLayoutScreenSize.png) from pathwright).

## Good luck! 😃 

### PS: Incase you want to reach out, please send me a message on slack (@Rose Wanjohi).

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Takhmina175 AND @okusarobert 
Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.

- [ ] Fix HTML validation [HTML Validation Screenshort](https://user-images.githubusercontent.com/29689273/93972127-21f1d600-fd8b-11ea-8bb6-91a6e9c01c21.png). You can check HTML validations in [validator.w3.org](https://validator.w3.org/)
- [ ] The live demo link doesn't work.
- [ ] Add .DS_Store file to gitignore because it is not related to the project.
- [ ] Increase the top of Articles heading

|[Source Page](https://www.smashingmagazine.com/)|[Clone Page](https://rawcdn.githack.com/Takhmina175/SmashingMagazine-ClonePage/3b4ff840a0db98f1ed85d6b90d083feed6a31b74/index.html)|
|:---:|:---:|
|source-page|clone|



##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by acushlakoncept — APPROVED** [review]
# Status: PROJECT APPROVED  🎉 🚀

Hi, @okusarobert and @Takhmina175  congratulations on completing your project and taking the time to implement the changes requested by the TSEs.  I see you have successfully implemented all the changes requested by the previous TSE. 

I will go ahead and mark this project as complete, feel free to merge when you are ready. All the best with the next project. 

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Pull request merged**
